version: "3"
services:

  db:
    container_name: xanadu-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: duncan
    ports:
      - "3306:3306"
    networks:
      - xanadu-networks

  app:
    container_name: xanadu-app
    command: sh -c "sleep 10"
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-app
    image: xanadu-app
    ports:
      - "8080:8080"
    networks:
      - xanadu-networks
networks:
  xanadu-networks:


