spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      javax..persistence.validation.mode: none
#  mvc:
#    throwExceptionIfNoHandlerFound: true
#  resources:
#    add-mappings: false
#logging:
#  level:
#    sql: debug
#    org.hibernate.orm.jdbc.bind: trace
server:
  servlet.session:
    timeout: 30000000
    cookie:
      http-only: true
      secure: true
#  error:
#    whitelabel:
#      enabled: false