spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: debug
#    org.hibernate.orm.jdbc.bind: trace